### ISSUE TITLE
EPIC: Expose XB performance analytics data to users

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#79]
Since XB personalizes content that cannot be tracked in Google Analytics so we need a way to expose that data to users.

To achieve this we will be targeting the following for v6 Release:
- [ ] [To add a way to collect views on XBs on a webpage for further analysis](https://github.com/humanmade/altis-analytics/issues/75)
- [ ] [Metrics to track in an XB](https://github.com/humanmade/altis-analytics/issues/78)
- [ ] [Provide a way to allow users to set a conversion goal within experience blocks](https://github.com/humanmade/altis-analytics/issues/76)
- [ ] [Provide a way to view CTA conversion rate](https://github.com/humanmade/altis-analytics/issues/77)

**Comment by PriyaBhatia0210** [comment]
Closing this epic as some of these issues are either closed or are being tracked someplace else.
